services:
  - type: web
    name: book-review-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: book-review-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: book-review-db
    databaseName: book_review_db
    user: book_review_user
